title: MongoDB AirBnb Workshop
description: Hands-on experience with MongoDB
baseurl: "/mongodb-airbnb-workshop"
url: "https://simonegaiera.github.io"
remote_theme: mmistakes/minimal-mistakes@master
plugins:
  - jekyll-include-cache
classes: wide
layout: single
sidebar:
  nav:
    - main
    - docs
