apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-workshop-nginx-config
  labels:
    {{- include "aibnb-workshop-nginx.labels" . | nindent 4 }}
data:
  custom-nginx.conf: |
    {{ .Values.nginx.config | nindent 4 }}