apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airbnb-workshop-nginx.fullname" . }}-configmap
  labels:
    {{- include "airbnb-workshop-nginx.labels" . | nindent 4 }}
data:
  custom-nginx.conf: |
    {{ .Values.nginx.config | nindent 4 }}