apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "airbnb-workshop-nginx.fullname" . }}-pv
  labels:
    {{- include "airbnb-workshop-nginx.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.volumeSize | quote }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: {{ .Values.nfsServer | quote }}
