apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airbnb-workshop-nginx.fullname" . }}-pvc
  labels:
    {{- include "airbnb-workshop-nginx.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumeSize | quote }}
  volumeName: {{ include "airbnb-workshop-nginx.fullname" . }}-pv
