{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.secret.data.tls.crt | b64enc }}
  tls.key: {{ .Values.secret.data.tls.key | b64enc }}
{{- end }}