POST http://localhost:5000/api/listingsAndReviews/20000000/reviews
Content-Type: application/json

{
    "_id": "20000000",
    "date": "2025-03-20T19:31:43.748Z",
    "listing_id": "20000000",
    "review_id": "10006546",
    "reviewer_name": "test",
    "comments": "http test"
}
