apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "redis.fullname" .) }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
