apiVersion: v1
kind: ConfigMap
metadata:
  name: mdb-nginx-config-cm
  labels:
    {{- include "mdb-nginx.labels" . | nindent 4 }}
data:
  custom-nginx.conf: |
    {{ .Values.nginx.config | nindent 4 }}