# Default values for mdb-openvscode.

replicaCount: 1

image:
  repository: 979559056307.dkr.ecr.us-east-2.amazonaws.com/ai-arena-mdb-openvscode
  pullPolicy: Always  # IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: ""
  name: ""

hostNetwork: false

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

securityContext: {}

service:
  type: ClusterIP
  ports:
    - name: openvscode
      port: 3000
      targetPort: 3000
    - name: web
      port: 3001
      targetPort: 3001
    - name: mongodb-api
      port: 5000
      targetPort: 5000
    - name: postgres-api
      port: 5001
      targetPort: 5001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: "1500m"
    memory: "2Gi"
  limits:
    cpu: "3000m"
    memory: "4Gi"

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

persistence:
  enabled: true
  fileSystemId: ""
  accessMode: ReadWriteMany
  size: 250Mi
  storageClass: ""
  annotations: {}

openvscode:
  user: ""

# Scenario configuration - these are typically overridden by Terraform
scenarioConfig:
  database:
    mongodb: false
    postgres: false
  llm:
    mcp: false

# Environment variables for MCP connections
env: []

extraEnv: []

# Results Processor Configuration
resultsProcessor:
  enabled: false
  image:
    repository: maven
    tag: "3.9.11-amazoncorretto-21-debian"
    pullPolicy: IfNotPresent

nodeSelector: {}

tolerations: []

affinity: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 1
