{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scenario-definition.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scenario-definition.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "scenario-definition.selectorLabels" . | nindent 4 }}
{{- end }}
