apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  labels:
    {{- include "mdb-openvscode.labels" . | nindent 4 }}
data:
  user.json: |-
    {
      "user": "{{ .Values.openvscode.user }}"
    }
  startup.sh: |-
    {{ .Files.Get "files/startup.sh" | nindent 4 }}
  user_operations.sh: |-
    {{ .Files.Get "files/user_operations.sh" | nindent 4 }}
  openvscode_extensions.sh: |-
    {{ .Files.Get "files/openvscode_extensions.sh" | nindent 4 }}
