apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airbnb-workshop-openvscode.fullname" . }}-configmap
  labels:
    {{- include "airbnb-workshop-openvscode.labels" . | nindent 4 }}
data:
  user.conf: |
    {{ .Values.openvscode.user | nindent 4 }}
  aws_route53_record_name.conf: |
    {{ .Values.aws_route53_record_name.user | nindent 4 }}
  startup.sh: |-
    {{ .Files.Get "files/startup.sh" | nindent 4 }}
