apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-efs-pv
spec:
  capacity:
    storage: {{ .Values.volumeSize | quote }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: {{ .Values.nfsServer | quote }}
