apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airbnb-workshop-openvscode.fullname" . }}-pvc
  labels:
    {{- include "airbnb-workshop-openvscode.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumeSize | quote }}
  # selector:
  #   matchLabels:
  #     app: {{ include "airbnb-workshop-openvscode.fullname" . }}-pv
  volumeName: {{ include "airbnb-workshop-openvscode.fullname" . }}-pv
