title: MongoDB Airbnb GameDay
title_separator: ""
subtitle: ""
description: Hands-on experience with MongoDB
baseurl: "/"
url: "https://mongogameday.com"
remote_theme: mmistakes/minimal-mistakes@master
logo: "/assets/images/logo.png"
breadcrumbs: false 
plugins:
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "docs"
include: ["_pages"]
