title: MongoDB Airbnb GameDay
title_separator: ""
subtitle: ""
description: Hands-on experience with MongoDB
baseurl: "/"
url: "https://mongogameday.com"
remote_theme: mmistakes/minimal-mistakes@master
logo: "/assets/images/logo.png"
breadcrumbs: false 
plugins:
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "docs"
include: ["_pages"]
