{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.litellm.config | toYaml | nindent 4 }}
{{- end }}
