{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.litellm.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.litellm.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
