replicaCount: 1

image:
  repository: gitpod/openvscode-server
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

labels:
  app.kubernetes.io/name: airbnb-workshop-openvscode
  app.kubernetes.io/instance: airbnb-workshop-openvscode

selectorLabels:
  app.kubernetes.io/name: airbnb-workshop-openvscode
  app.kubernetes.io/instance: airbnb-workshop-openvscode

service:
  type: ClusterIP
  ports:
    - name: openvscode
      port: 3000
      targetPort: 3000
    - name: web
      port: 3001
      targetPort: 3001
    - name: api
      port: 5000
      targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}
# resources:
#   requests:
#     cpu: 1
#     memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nfsServer: ""
volumeSize: 100Mi

openvscode:
  user: ""
  aws_route53_record_name: ""

nodeSelector: {}

tolerations: []

affinity: {}